previews:
  generation: automatic
services:
- type: web
  name: Test-Full-Stack-App-Frontend
  runtime: node
  repo: https://github.com/CameronBeneteau/Test-Full-Stack-App
  plan: free
  region: ohio
  buildCommand: yarn && yarn build
  startCommand: yarn start
  rootDir: frontend
- type: web
  name: Test-Full-Stack-App-Backend
  runtime: python
  repo: https://github.com/CameronBeneteau/Test-Full-Stack-App
  plan: free
  region: ohio
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn -b 0.0.0.0:5555 main:app
  rootDir: backend
version: "1"
