name: PR Deployment to Render

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set PR Number
        run: echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV

      - name: Deploy Backend to Render
        if: github.event.action != 'closed'
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-cvcngvd6l47c73fkhu3g/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "serviceId": "srv-cvcngvd6l47c73fkhu3g",
              "envVars": [
                {
                  "key": "RENDER_EXTERNAL_PR_NUMBER",
                  "value": "${{ env.PR_NUMBER }}"
                }
              ]
            }'

      - name: Deploy Frontend to Render
        if: github.event.action != 'closed'
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-cvcn9s52ng1s7390e1cg/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "serviceId": "srv-cvcn9s52ng1s7390e1cg",
              "envVars": [
                {
                  "key": "NEXT_PUBLIC_API_BASE_URL",
                  "value": "https://test-full-stack-app-backend-pr-${{ env.PR_NUMBER }}.onrender.com"
                }
              ]
            }'

  cleanup:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Delete Backend PR Deployment
        run: |
          curl -X DELETE "https://api.render.com/v1/services/srv-cvcngvd6l47c73fkhu3g" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

      - name: Delete Frontend PR Deployment
        run: |
          curl -X DELETE "https://api.render.com/v1/services/srv-cvcn9s52ng1s7390e1cg" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
